development:
  dialect: postgres
  database: genos_development
  user: genos
  password: genos
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://genos:genos@127.0.0.1:5432/genos_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://genos:genos@127.0.0.1:5432/genos_production?sslmode=disable"}}
